apiVersion: v1
kind: Service
metadata:
  name: parking-front-end
spec:
  type: NodePort
  selector:
    app: parking-front-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30087
